# Generated by Django 5.1.2 on 2024-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created']},
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['created'], name='rate_author_created_59fc0d_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['title'], name='rate_link_title_7163e4_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created'], name='rate_review_created_12e180_idx'),
        ),
    ]
