# Generated by Django 5.1.2 on 2024-11-01 07:19

import rate.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_alter_author_options_alter_link_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='allow_mail',
            field=models.BooleanField(default=True, verbose_name='Allow clients to send emails to author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', validators=[rate.services.validate_avatar]),
        ),
    ]
