# Generated by Django 5.1.2 on 2024-11-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_alter_author_allow_mail_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(),
        ),
    ]
